# Generated by Django 5.1.6 on 2025-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар пользователя. Можно оставить пустым.",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Страна проживания пользователя. Можно оставить пустым.",
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Уникальный адрес электронной почты пользователя.",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя.",
                max_length=150,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Фамилия пользователя.",
                max_length=150,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона пользователя. Можно оставить пустым.",
                max_length=15,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
