# Generated by Django 5.1.4 on 2025-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="catalog/product_images",
                verbose_name="Фото",
            ),
        ),
    ]
