# Generated by Django 5.1.6 on 2025-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.FloatField(
                help_text="Введите цену товара", verbose_name="Цена товара"
            ),
        ),
    ]
