# Generated by Django 5.1.6 on 2025-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("unpublished", "Не опубликован"),
                    ("draft", "Черновик"),
                    ("pending_review", "Ожидает проверки"),
                    ("published", "Опубликован"),
                ],
                default="unpublished",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
