# Generated by Django 5.1.6 on 2025-02-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    ("can_change_category", "Can change category"),
                    ("can_delete_category", "Can delete category"),
                ],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
